services:
  - type: web
    name: hear-me-out
    env: docker
    plan: starter
    region: oregon
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
    autoDeploy: true
    disk:
      name: sqlite-data
      mountPath: /app/prisma
      sizeGB: 1 