services:
  - type: web
    name: hear-me-out
    env: docker
    region: oregon # or choose another region
    plan: starter # or choose another plan
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        sync: false # This will be set manually in Render dashboard
      - key: NEXTAUTH_SECRET
        sync: false # This will be set manually in Render dashboard
      - key: DATABASE_URL
        value: file:./prisma/dev.db
    disk:
      name: sqlite-data
      mountPath: /app/prisma
      sizeGB: 1 